# Generated by Django 4.0.4 on 2022-05-12 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Entry date')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.AddField(
            model_name='community',
            name='participants',
            field=models.ManyToManyField(through='communities.CommunityParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='communityparticipant',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='communityparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
        migrations.AlterUniqueTogether(
            name='communityparticipant',
            unique_together={('community', 'participant')},
        ),
    ]
