# Generated by Django 4.0.4 on 2022-05-14 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_communityparticipant_community_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='community',
            name='participants',
            field=models.ManyToManyField(related_name='communities', through='communities.CommunityParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
