# Generated by Django 4.0.4 on 2022-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_creator_alter_community_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityparticipant',
            options={'verbose_name': 'Community Participant', 'verbose_name_plural': 'Communities Participants'},
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
    ]
