# Generated by Django 4.0.4 on 2022-05-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_communityparticipant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityparticipant',
            options={'verbose_name': 'Community participant', 'verbose_name_plural': 'Communities participants'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='participants_number',
        ),
    ]
