# Generated by Django 4.0.4 on 2022-05-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_communityparticipant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='custom_id',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Custom id'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
