# Generated by Django 4.0.4 on 2022-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_community_custom_id_alter_community_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='custom_id',
            field=models.SlugField(null=True, unique=True, verbose_name='Custom id'),
        ),
    ]
