# Generated by Django 4.0.4 on 2022-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End date'),
        ),
    ]
