# Generated by Django 4.0.4 on 2022-05-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='custom_id',
        ),
    ]
