# Generated by Django 4.0.4 on 2022-05-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='technologies',
            field=models.ManyToManyField(related_name='users', to='base.technology', verbose_name='Technologies'),
        ),
    ]
